sudo: false

language: node_js

node_js:
  - 7

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - yarn

script:
  - yarn test
  - yarn lint
  - yarn jscs
  - yarn prebuild
  - yarn build
  - yarn build:html
